# WARNING: Replace values before committing to any VCS.
# In production use a Secrets Manager (AWS Secrets Manager, Vault, etc.)
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  namespace: dev
type: Opaque
stringData:
  DB_PASSWORD: "Asad@1234"
  SECRET_KEY: "saista-bakers-super-secure-prod-key-2024"
  JWT_SECRET: "saista-bakers-super-secure-prod-key-2024"
